ritopls/config/routes.rb
Ritopls::Application.routes.draw do

  root 'champions#index'

  post '/find' => 'users#find'
  post '/finduser' => 'users#userfind'
  post '/login' => 'sessions#create'
  post '/signup' => 'users#create'
  post '/votebalanced' => 'champions#votebalanced'
  post '/votebuff' => 'champions#votebuff'
  post '/votenerf' => 'champions#votenerf'
  post '/voterework' => 'champions#voterework'
  post '/votevupdate' => 'champions#votevupdate'
  post '/fingerprint' => 'fingerprints#fingerprint'
  post '/comment' => 'comments#create'
  post '/edit' => 'champions#show'

  get 'champions/balanced' => 'champions#balanced', as: :balanced
  get 'champions/buff' => 'champions#buff', as: :buff
  get 'champions/nerf' => 'champions#nerf', as: :nerf
  get 'champions/rework' => 'champions#rework', as: :rework
  get 'champions/vupdate' => 'champions#vupdate', as: :vupdate
  get 'champions/:id' => 'champions#show', as: :champion
  get 'comments/:id/edit' => 'comments#edit', as: :edit_comment
  patch 'comment/:id' => 'comments#update', as: :comment_update
  delete 'comments/:id' => 'comments#destroy', as: :destroy

end

ritopls/app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :votes, type: Integer
  field :text, type: String
  field :username, type: String

  belongs_to :user
  belongs_to :champion
end
	

ritopls/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    begin
		  current_user = User.find(cookies['id'])
      @comment = Comment.new(params.require(:comment).permit(:text, :champion_id))
      @comment[:user_id] = current_user[:id]
      @comment[:username] = current_user[:username]
    rescue
      redirect_to :back
    end
  		if @comment[:text] == ""
  		  redirect_to :back
  		else @comment.save
		    redirect_to :back
		  end
	end

  def destroy
    begin
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to :back
    rescue
      redirect_to :back
    end
           
  end

  def edit
    begin
      @comment = Comment.find(params[:id])
      @champion = Champion.find_by(id: @comment[:champion_id].to_i )
      @comments = Comment.where(champion_id: @champion[:id].to_s)
    rescue
      redirect_to :back
    end
 
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment[:text].empty? == true
        @comment.destroy
        redirect_to champion_path(@comment[:champion_id].to_i)
    else 
      @comment.update_attributes(params.require(:comment).permit(:text))
      redirect_to champion_path(@comment[:champion_id].to_i)
    end
  end

end

ritopls/app/helpers/comments_helper.rb
module CommentsHelper
end

ritopls/app/views/comments/edit.html.erb
<div class='container showview'>
	<h1><%= @champion.name %></h1>
	<div class="well championwell">
			<%= image_tag @champion.key + '_Square_0.jpeg', class: "champions" %>	
	<div class="btn-group" id="showpg">
		<button type="button" class="btn btn-primary"><span id='balancednum'>Balanced <br><br><%= @champion.balanced %></span></button>
		<button type="button" class="btn btn-success"><span id='buffnum'>Buff <br><br><%= @champion.buff %></span></button>
		<button type="button" class="btn btn-danger"><span id='nerfnum'>Nerf <br><br><%= @champion.nerf %></span></button>
		<button type="button" class="btn btn-warning"><span id='reworknum'>Rework <br><br><%= @champion.rework %></span></button>
		<button type="button" class="btn btn-info"><span id='vupdatenum'>Visual Update <br><br><%= @champion.visual_update %></span></button>
	</div>
	</div>
	

	<ul class="list-group">
		<% @comments.each do |comment| %>
			<li class="list-group-item" ><%= comment.text %></li>
			<div id="commentuser">Posted By: <%= comment.username %></div>
			<% if comment.user_id.to_s == cookies[:id] %>
			<div class="delete" id='<%= comment.user_id %>'>
			<%= link_to "Edit", edit_comment_path(comment) %>
			<%= link_to "Delete", destroy_path(comment), method: :delete %>
			</div>
			<% end %>
		<% end %>
	</ul>
</div>
<div class="container blank">
</div>
<div class="navbar navbar-default navbar-fixed-bottom">
	<div class="container">
		<%= form_for @comment, url: comment_update_path do |f| %>
		<div class="input-group post">
			<%= f.text_field :text, class: "form-control" %>
			<%= f.hidden_field :champion_id, :value => @champion.id %>
			<span class="input-group-btn"><% if cookies[:id] %><%= f.submit "Edit", class: "btn btn-default" %><% else %><%= f.submit "Login to post", class: "btn btn-default disabled" %><% end %></span>
		<% end %>
		</div>
	</div>
</div>