ritopls/config/routes.rb
Ritopls::Application.routes.draw do

  root 'champions#index'

  post '/find' => 'users#find'
  post '/finduser' => 'users#userfind'
  post '/login' => 'sessions#create'
  post '/signup' => 'users#create'
  post '/votebalanced' => 'champions#votebalanced'
  post '/votebuff' => 'champions#votebuff'
  post '/votenerf' => 'champions#votenerf'
  post '/voterework' => 'champions#voterework'
  post '/votevupdate' => 'champions#votevupdate'
  post '/fingerprint' => 'fingerprints#fingerprint'
  post '/comment' => 'comments#create'
  post '/edit' => 'champions#show'

  get 'champions/balanced' => 'champions#balanced', as: :balanced
  get 'champions/buff' => 'champions#buff', as: :buff
  get 'champions/nerf' => 'champions#nerf', as: :nerf
  get 'champions/rework' => 'champions#rework', as: :rework
  get 'champions/vupdate' => 'champions#vupdate', as: :vupdate
  get 'champions/:id' => 'champions#show', as: :champion
  get 'comments/:id/edit' => 'comments#edit', as: :edit_comment
  patch 'comment/:id' => 'comments#update', as: :comment_update
  delete 'comments/:id' => 'comments#destroy', as: :destroy

end

ritopls/app/models/champion.rb
class Champion
  include Mongoid::Document
  field :name, type: String
  field :id, type: Integer
  field :title, type: String
  field :key, type: String
  field :balanced, type: Integer
  field :buff, type: Integer
  field :nerf, type: Integer
  field :rework, type: Integer
  field :visual_update, type: Integer

  has_many :comments

end

ritopls/app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
	def index
		@champions = Champion.all
	end

	def balanced
		@champions = Champion.all
	end

	def buff
		@champions = Champion.all
	end

	def nerf
		@champions = Champion.all
	end

	def rework
		@champions = Champion.all
	end

	def vupdate
		@champions = Champion.all
	end

	def show
		# begin
		# 	@current_user ||= User.find_by(id: cookies[:id])
		# rescue
		# 	@current_user = nil
		# end
		@champion = Champion.find(params[:id].to_i)
		begin
			@comments = Comment.where(champion_id: params[:id])
		rescue
			@comments = nil
		end
	end

	def votebalanced
		useragent = Digest::SHA1.hexdigest(request.user_agent + request.remote_ip)
  		@fingerprint = Fingerprint.find_by({hash: useragent})
		datajson = request.body.read
		@champion = Champion.find_by({key: datajson})
  		@fingerprint[datajson] ||= [0,0,0]

		if @fingerprint[datajson][0] != 1
			@champion[:balanced] += 1
			@champion[:buff] -= 1 if @fingerprint[datajson][0] == 2 
			@champion[:nerf] -= 1 if @fingerprint[datajson][0] == 3
			@champion.save
			@fingerprint[datajson][0] = 1
			@fingerprint.upsert
		end
	end

	def votebuff
		useragent = Digest::SHA1.hexdigest(request.user_agent + request.remote_ip)
  		@fingerprint = Fingerprint.find_by({hash: useragent})
		datajson = request.body.read
		@champion = Champion.find_by({key: datajson})
  		@fingerprint[datajson] ||= [0,0,0]

		if @fingerprint[datajson][0] != 2
			@champion[:buff] += 1
			@champion[:balanced] -= 1 if @fingerprint[datajson][0] == 1
			@champion[:nerf] -= 1 if @fingerprint[datajson][0] == 3
			@champion.save
			@fingerprint[datajson][0] = 2
			@fingerprint.upsert
		end
	end

	def votenerf
		useragent = Digest::SHA1.hexdigest(request.user_agent + request.remote_ip)
  		@fingerprint = Fingerprint.find_by({hash: useragent})
  		datajson = request.body.read
		@champion = Champion.find_by({key: datajson})
		@fingerprint[datajson] ||= [0,0,0]

		if @fingerprint[datajson][0] != 3
			@champion[:nerf] += 1
			@champion[:balanced] -= 1 if @fingerprint[datajson][0] == 1
			@champion[:buff] -= 1 if @fingerprint[datajson][0] == 2
			@champion.save
			@fingerprint[datajson][0] = 3
			@fingerprint.upsert
		end
	end

	def voterework
		useragent = Digest::SHA1.hexdigest(request.user_agent + request.remote_ip)
  		@fingerprint = Fingerprint.find_by({hash: useragent})
  		datajson = request.body.read
		@champion = Champion.find_by({key: datajson})
  		@fingerprint[datajson] ||= [0,0,0]

		if @fingerprint[datajson][1] == 0
			@champion[:rework] += 1
			@champion.save
			@fingerprint[datajson][1] = 1
			@fingerprint.upsert
		else
			@champion[:rework] -= 1
			@champion.save
			@fingerprint[datajson][1] = 0
			@fingerprint.upsert
		end
	end

	def votevupdate
		useragent = Digest::SHA1.hexdigest(request.user_agent + request.remote_ip)
  		@fingerprint = Fingerprint.find_by({hash: useragent})
  		datajson = request.body.read
		@champion = Champion.find_by({key: datajson})
  		@fingerprint[datajson] ||= [0,0,0]
  		
		if @fingerprint[datajson][2] == 0
			@champion[:visual_update] += 1
			@champion.save
			@fingerprint[datajson][2] = 1
			@fingerprint.upsert
		else
			@champion[:visual_update] -= 1
			@champion.save
			@fingerprint[datajson][2] = 0
			@fingerprint.upsert
		end
	end
end

ritopls/app/helpers/champions_helper.rb
module ChampionsHelper
end

ritopls/app/views/champions/_champions.html.erb
<div class="mycontainer">
<div class="topcontainer">
	<div class="btn-group buttoncontainer">
	  <button type="button" class="btn btn-default disabled">Sort By:</button>
	  <%= link_to "Name", root_path, class: "btn btn-default" %>
	  <%= link_to "Balanced", balanced_path, class: "btn btn-primary" %>
	  <%= link_to "Buff", buff_path, class: "btn btn-success" %>
	  <%= link_to "Nerf", nerf_path, class: "btn btn-danger" %>
	  <%= link_to "Rework", rework_path, class: "btn btn-warning" %>
	  <%= link_to "Visual Update", vupdate_path, class: "btn btn-info" %>
	</div>
</div>
<% @champion_names.each do |champion| %>
		<div id="characters" class="btn-group characters">
			<%= link_to champion_path(champion), class: "champions", id: champion.key do %>
				<%= image_tag champion.key + '_Square_0.jpeg' %>
			<% end %>
			<div class="votes">
				  <button type="button" class="btn btn-primary vote"><span id='balancednum'><%= champion.balanced %></span></button>
				  <button type="button" class="btn btn-success vote"><span id='buffnum'><%= champion.buff %></span></button>
				  <button type="button" class="btn btn-danger vote"><span id='nerfnum'><%= champion.nerf %></span></button>
				  <button type="button" class="btn btn-warning vote"><span id='reworknum'><%= champion.rework %></span></button>
				  <button type="button" class="btn btn-info vote"><span id='vupdatenum'><%= champion.visual_update %></span></button>
			</div>
			<div class="champname"><%= champion.name %></div>
		</div>
		<div class="stats <%= champion.key %>">
			<div class="btn-group">
			  <button type="button" class="btn btn-primary"><%= champion.balanced %></button>
			  <button type="button" class="btn btn-primary">Balanced</button>
			</div>
			<div class="btn-group">
			  <button type="button" class="btn btn-success"><%= champion.buff %></button>
			  <button type="button" class="btn btn-success">Buff</button>
			</div>
			<div class="btn-group">
			  <button type="button" class="btn btn-danger"><%= champion.nerf %></button>
			  <button type="button" class="btn btn-danger">Nerf</button>
			</div>
			<div class="btn-group">
			  <button type="button" class="btn btn-warning"><%= champion.rework %></button>
			  <button type="button" class="btn btn-warning">Rework</button>
			</div>
  		</div>
<% end %>
</div>

ritopls/app/views/champions/balanced.html.erb
<div class="jumbotron">
OP or Not OP
</div>

<% @champion_names = @champions.sort_by { |champion| [-champion[:balanced], champion[:name]] } %>
<%= render 'champions', object: @champion_names %>

ritopls/app/views/champions/buff.html.erb
<div class="jumbotron">
OP or Not OP
</div>

<% @champion_names = @champions.sort_by { |champion| [-champion[:buff], champion[:name]] } %>
<%= render 'champions', object: @champion_names %>

ritopls/app/views/champions/index.html.erb
<div class="jumbotron">
OP or Not OP
</div>

<% @champion_names = @champions.sort_by { |champion| champion[:name] }%>
<%= render 'champions', object: @champion_names %>

ritopls/app/views/champions/nerf.html.erb
<div class="jumbotron">
OP or Not OP
</div>

<% @champion_names = @champions.sort_by { |champion| [-champion[:nerf], champion[:name]] } %>
<%= render 'champions', object: @champion_names %>

ritopls/app/views/champions/rework.html.erb
<div class="jumbotron">
OP or Not OP
</div>

<% @champion_names = @champions.sort_by { |champion| [-champion[:rework], champion[:name]] } %>
<%= render 'champions', object: @champion_names %>

ritopls/app/views/champions/show.html.erb
<!-- <script>
$(window).bind('page:change', function() {
	var cookie = document.cookie.slice(3).split(";")[0]
	$('#post').click(function(){
		console.log(cookie)
		   $.ajax({
		      url: "/comment",
		      data: cookie,
		      method: 'post',
		      dataType: 'json',
		      success: function(data) {
		        console.log(data)
      		}
 	   });
	})
})
</script> -->

<div class='container'>
	<div class="well championwell">
			<%= image_tag @champion.key + '_Square_0.jpeg', class: "champions" %>	
	<div class="btn-group" id="showpg">
		<button type="button" class="btn btn-primary"><span id='balancednum'>Balanced <br><br><%= @champion.balanced %></span></button>
		<button type="button" class="btn btn-success"><span id='buffnum'>Buff <br><br><%= @champion.buff %></span></button>
		<button type="button" class="btn btn-danger"><span id='nerfnum'>Nerf <br><br><%= @champion.nerf %></span></button>
		<button type="button" class="btn btn-warning"><span id='reworknum'>Rework <br><br><%= @champion.rework %></span></button>
		<button type="button" class="btn btn-info"><span id='vupdatenum'>Visual Update <br><br><%= @champion.visual_update %></span></button>
	</div>
	</div>
	<h1><%= @champion.name %></h1>
	<%= form_for(:comment, url: comment_path) do |f| %>
		<%= f.text_field :text %>
		<%= f.hidden_field :champion_id, :value => @champion.id %>
		<%= f.submit "Post" %>
	<% end %>
	<div>
	<ul class="list-group">
		<% @comments.each do |comment| %>
			<li class="list-group-item"><%= comment.text %></li>
		<% end %>
	</div>
	</ul>

</div>

ritopls/app/views/champions/vupdate.html.erb
<div class="jumbotron">
OP or Not OP
</div>

<% @champion_names = @champions.sort_by { |champion| [-champion[:visual_update], champion[:name]] } %>
<%= render 'champions', object: @champion_names %>